### ISSUE TITLE
Could we have another option to format the entire document?

### ISSUE THREAD

**Issue by AdrianJMartin** [federomero/pretty-json#14]
Quite often I paste in a JSON dump, and forget to select all before attempting to prettify it!

**Comment by TeardropInc** [comment]
I agree with these guys and the way I would imagine it would work (and assumed at first) is the following conditions:

1. If the file has a JSON extension, format without requiring selection. (I believe it does this already)
2. If the file has no extension (e.g. new, unsaved file), *assume* it is JSON and just format everything without requiring selection.
3. If the file has a non-JSON extension then require selection.

**Comment by lexicalunit** [comment]
I've added support for this in commit 1168bd4. The change also allows anyone to specify a list of grammars that they want to have "format entire file" support for. The default is `['source.json', 'text.plain.null-grammar']`. Expect a new release soon!

**Comment by baziliolg** [comment]
Is it possible to add an option to prettify/minify **only selected text** even if the file *is* json? An example - Amazon CloudFormation template file. I want to prettify the whole file first and then minify only objects that I select.

**Comment by lexicalunit** [comment]
I haven't tried (on my phone right now) but I think it should work that way currently, @baziliolg. Is it not working for you?

**Comment by baziliolg** [comment]
@lexicalunit,
unfortunately it does not work.
Prettify or minify is working only when nothing is selected, so it is applied to the whole file. If text is selected, nothing happens when I select menu Packages - Pretty JSON - Minify.

**Comment by lexicalunit** [comment]
I'm betting the issue is that the selected text isn't valid JSON data. Here's [a video showing me minifying selected example JSON data](https://youtu.be/ZG9smLewKFs) within a larger JSON file.

The selected text has to be parsed as complete and valid JSON data in order for the prettifier/minifier libraries to correctly process it. For example, in the video if I had selected the trailing `,` I would have got a warning notification indicating a JSON syntax error.

Could you provide some example JSON data and indicate which parts you're selecting when the command isn't working? There could be a bug in the code that is causing the issue you're seeing and if I can re-create the bug on my machine I'm sure I can fix it for you :)

**Comment by baziliolg** [comment]
@lexicalunit thank you very much for detailed explanation!
Turns out that it did not work because I kept selecting key AND value.
For example, I'd like the following JSON snippet to become one-liner, and I selected everything including `"HornetQPort"` because this was intuitive to me

        "HornetQPort": {
            "Type": "String",
            "Default": "10100",
            "Description": "HornetQPort check port"
        }

and it did not work. I never thought that I have to select only {...} part.

There is also an observation: there were no error messages popping up even though "Notify on parse error" option is checked by default. After turning this option off and on again the messages about wrong JSON syntax started showing.

**Comment by lexicalunit** [comment]
Oh weird, that's not good about not getting the notifications. It's possible that's a bug in Atom cause I'm just doing a straightforward `atom.config.get 'pretty-json.notifyOnParseError'`. Hrmmm. Good to keep an eye on it if I see other reports coming in. Thanks for the report! Glad you got it working also 👍
