### ISSUE TITLE
Please Add Keymap

### ISSUE THREAD

**Issue by rahulbsw** [federomero/pretty-json#28]
It will be great to have shortcut for , please add Keymap prettify and minify

**Comment by november-eleven** [comment]
:+1:

**Comment by lexicalunit** [comment]
I prefer not to provide keymaps with the package itself as you can add your own keymaps very easily: http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/

If a package provides a keymap itself, then it may overlap with existing keymaps. In general, most packages that do not come default with Atom tend not to have keymaps because of this issue.
