### ISSUE TITLE
Crash when trying to format big JSON

### ISSUE THREAD

**Issue by rugk** [federomero/pretty-json#30]
On https://realfavicongenerator.net (@realfavicongenerator) you can also get JSON files for their [API](https://realfavicongenerator.net/api/non_interactive_api#.Vpuc_FIxmUk). In them the image/favicon can added base64 encoded.

So when I save the RAW file (which only consists of one line) I can open it in Atom.
However when I use this package Atom crashes.
Possibly this is a more general error with Atom, so [I've reported it in their repo](https://github.com/atom/atom/issues/10465) too.

Here you can find the test files: https://gist.github.com/rugk/c23a5978e2f037b1ffaa

Atom 1.4.0
Windows 7

**Comment by lexicalunit** [comment]
I've added a unit test in commit 668ae60 which loads https://gist.github.com/rugk/c23a5978e2f037b1ffaa and runs prettify on it. Right now I've got it passing. It may have been improvements that Atom's core since this issue was reported that is responsible for this now working. Or it could have been the move to using `json-bigint`. Regardless, this now works and we should avoid regressions in the future. Thanks for reporting the issue! Expect a new release out very soon.
