### ISSUE TITLE
JSON Pretty: parse issue: [Object object]

### ISSUE THREAD

**Issue by ChrisJefferson** [federomero/pretty-json#37]
Whenever I try to run the package, I always get the error message in the title of the issue..

**Comment by lexicalunit** [comment]
@ChrisJefferson Are you trying to run a Prettify, Minify, or Jsonify command? I'm going to update the error message so that it's easier to tell in the future, but for now it would be very helpful to me to know which command you're attempting to run.

**Comment by lexicalunit** [comment]
So I _think_ the issue is there's a JSON syntax error in the code that you're trying to prettify. Right now you're getting a JSON parse error, but the notification isn't actually showing any useful information. You're just getting that worthless error message, `[Object object]`. #38 will fix the error message so that you'll have a much better idea of what is going wrong here. In the meantime, it would probably be very useful to you to install [linter-jsonlint](https://atom.io/packages/linter-jsonlint) and then paste the JSON code you're trying to prettify into a `.json` file and see if the linter identifies any syntax issues. You could also use something like http://jsonlint.com/ instead of installing another plugin.

**Comment by lexicalunit** [comment]
@ChrisJefferson I just published version 1.1.0 which should help resolve this issue for you. Please feel free to reopen if you continue to have problems with the plugin. Thanks for the report!

**Comment by ChrisJefferson** [comment]
Just to confirm, yes, my JSON was malformed (I had been provided with a massive JSON file I wanted to reformat and look at). Thanks!
