### ISSUE TITLE
SyntaxError: Unexpected "

### ISSUE THREAD

**Issue by jaiment** [federomero/pretty-json#54]
Hello.
I have Atom 1.9.0 and just installed this package and I get this message on my JSON, which I validated using jsonlint.com and Power JSON for Mac.
![2016-08-01_14-36-42](https://cloud.githubusercontent.com/assets/6313964/17306462/d4852e24-57f5-11e6-9e5a-803b39d163ab.png)

[https://gist.github.com/jaiment/33228e7c918ab6eb0993d68f5cdd0d03](url)

**Comment by lexicalunit** [comment]
The gist you posted is 404. If you can I'd like to get my hands on that JSON so I can do some testing and try to work out a solution. Can you post it here or try gist again?

**Comment by lexicalunit** [comment]
@jaiment, the `Prettify` command work for me on the JSON in your posted gist. This is the output I got: https://gist.github.com/lexicalunit/54fc59274ee8ec6a68e7868ddcadd7a0 Can you make sure that you don't have any text selected when you run the command? By design, pretty-json will run on selected text if there is any instead of the entire file. Maybe that's what's going on here?

Also are you running pretty-json version 1.4.1?

**Comment by jaiment** [comment]
Sure, JSON is attached.
:)

**Comment by jaiment** [comment]
Wow suddenly it worked, probably my mistake on the way of using prettify command, sorry.

**Comment by lexicalunit** [comment]
All good! Thanks for the bug report and for using the package :)

**Comment by jaiment** [comment]
I found that the error message appears when the JSON file is auto-generated
from a Macro Excel using .NET ....
Nice to find the reason ... here you may find the orinal JSON.
